// Question bank — "Which One's Real?" party game (v2)
// Each question: ONE verified real news story + 3 fakes.
// The real one is always the one that sounds the most fake.
//
// Tags (used by the filter stack):
//   segment — topic bucket (Animals, Sports, Disasters, ...)
//   region  — where it happened
//   era     — decade it happened
//   outlet  — where it's documented
//   date    — approximate ISO date of the event
// `link` is the verifiable source shown on the reveal.
// Every story in this bank has been manually verified against its source.
const QUESTIONS = [
  {
    segment: "Animals",
    region: "Australia",
    era: "1930s",
    outlet: "Wikipedia",
    date: "1932-10-01",
    real: "Army deploys machine guns in failed war against emus",
    source: "The Emu War, Western Australia, 1932 — the army lost to the birds.",
    link: "https://en.wikipedia.org/wiki/Emu_War",
    fakes: [
      "Farmers report record emu harvest after bumper season",
      "Village declares emergency after flock blocks main road",
      "New breeding program aims to boost local emu numbers",
    ],
  },
  {
    segment: "Business",
    region: "Europe",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2018-02-04",
    real: "KFC's UK chicken shortage so bad it swapped its logo for FCK",
    source: "Feb 2018 — a DHL logistics failure left KFC UK out of chicken for a week; the apology ads showed the logo rearranged as FCK.",
    link: "https://en.wikipedia.org/wiki/KFC",
    fakes: [
      "Fast food chain launches new spicy chicken burger",
      "Delivery app reports record holiday weekend orders",
      "Restaurant group cuts prices to win back customers",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1917-01-01",
    real: "Newspaper runs the headline \u201cMan bites dog\u201d in 1917",
    source: "A Belgian paper ran \u201cMan bites dog\u201d as a joke headline in 1917 — one of the earliest recorded uses.",
    link: "https://en.wikipedia.org/wiki/Man_bites_dog",
    fakes: [
      "Veterinarian warns about rising dog bite reports",
      "City passes new leash law for public parks",
      "Rescue group celebrates record dog adoptions",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1977-08-01",
    real: "Park ranger struck by lightning seven times — and lived",
    source: "Roy Sullivan, Shenandoah National Park ranger, survived seven strikes between 1942 and 1977 — Guinness-verified \u201chuman lightning rod\u201d.",
    link: "https://en.wikipedia.org/wiki/Roy_Sullivan",
    fakes: [
      "Meteorologists issue rare double-storm warning",
      "Lightning safety campaign hits record reach",
      "New sensor network tracks storms in real time",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1925-02-13",
    real: "Nation watches as thousands dig for a man trapped in a cave",
    source: "Floyd Collins, Kentucky, 1925 — a 20,000-person rescue effort made the cave collapse a national tragedy.",
    link: "https://en.wikipedia.org/wiki/Floyd_Collins",
    fakes: [
      "Caving group logs record-deep expedition in limestone",
      "Authorities close trail after rockfall warning",
      "Museum opens new exhibit on early explorers",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1997-07-18",
    real: "Alaska town names a 170-pound cat honorary mayor",
    source: "Stubbs of Talkeetna, Alaska — honorary mayor from 1997 until his death, drawing 30\u201340 visitors a day.",
    link: "https://en.wikipedia.org/wiki/Stubbs_(cat)",
    fakes: [
      "Vet opens new clinic to serve growing pet population",
      "Volunteers launch winter feeding program for strays",
      "Town council debates new rules on public pets",
    ],
  },
  {
    segment: "History",
    region: "North America",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1926-11-01",
    real: "Escape artist dies hours after a stranger punches his stomach",
    source: "Harry Houdini took a repeated punch to the abdomen during a strength-test stunt on Oct 31, 1926; he died the next morning.",
    link: "https://en.wikipedia.org/wiki/Harry_Houdini",
    fakes: [
      "Magician's estate settles long-running property dispute",
      "Celebrity chef announces new restaurant opening",
      "Veteran performer retires after 40-year career",
    ],
  },
  {
    segment: "Sports",
    region: "South America",
    era: "1950s",
    outlet: "Wikipedia",
    date: "1950-07-16",
    real: "Home fans watch their own team lose the World Cup final",
    source: "The Maracanazo, 1950 — Brazil lost the final at home to Uruguay in front of a stunned Maracan\u00e3 crowd.",
    link: "https://en.wikipedia.org/wiki/Uruguay_v_Brazil_(1950_FIFA_World_Cup)",
    fakes: [
      "Stadium sets record for largest single-match attendance",
      "National team announces new coach for next cycle",
      "Ticket prices scrapped after fan backlash",
    ],
  },
  {
    segment: "Sports",
    region: "South America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1986-06-22",
    real: "Player scores with his hand and calls it a gift from God",
    source: "Diego Maradona, 1986 World Cup — the \u201cHand of God\u201d goal, minutes before the Goal of the Century, same match.",
    link: "https://en.wikipedia.org/wiki/Diego_Maradona",
    fakes: [
      "Striker fined for simulating an injury",
      "Referee union introduces new card system",
      "Coach defends controversial last-minute substitution",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1997-05-11",
    real: "Computer beats the world chess champion for the first time",
    source: "May 1997 — Deep Blue became the first computer to beat the reigning world chess champion in a match.",
    link: "https://en.wikipedia.org/wiki/Deep_Blue_vs_Garry_Kasparov",
    fakes: [
      "Grandmaster wins tournament in record time",
      "Chess federation updates rating system",
      "New AI startup raises funding for board games",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1988-11-02",
    real: "Student's code infects a tenth of the internet in one weekend",
    source: "Robert Tappan Morris, 1988 — his \u201cworm\u201d hit roughly 10% of the connected internet, the first major one.",
    link: "https://en.wikipedia.org/wiki/Morris_worm",
    fakes: [
      "Security firm releases patch for popular email client",
      "University bans USB drives after data breach",
      "Tech giant unveils new antivirus product",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1999-09-23",
    real: "Space agency loses a mission because of one missing conversion",
    source: "Mars Climate Orbiter, 1999 — lost after one team worked in miles and another in meters.",
    link: "https://en.wikipedia.org/wiki/Mars_Climate_Orbiter",
    fakes: [
      "Rocket launch scrubbed over weather",
      "Mission control adds new safety checklist",
      "Probe sends back stunning images of red planet",
    ],
  },
  {
    segment: "Internet",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2017-07-01",
    real: "Millions of strangers paint on one giant shared canvas",
    source: "r/place, 2017 — over a million users placed ~16 million pixels on one 16,777,216-pixel canvas over 30 days.",
    link: "https://en.wikipedia.org/wiki/R/place",
    fakes: [
      "Museum opens digital art installation downtown",
      "Art collective launches collaborative mural project",
      "University students win design award for public art",
    ],
  },
  {
    segment: "History",
    region: "Europe",
    era: "1850s",
    outlet: "Wikipedia",
    date: "1858-06-15",
    real: "River stench so bad it shut down Parliament for a month",
    source: "The Great Stink, London 1858 — the Thames smelled so bad Parliament nearly moved; it forced the city's modern sewer system.",
    link: "https://en.wikipedia.org/wiki/Great_Stink",
    fakes: [
      "City council debates new waste collection route",
      "Health officials issue summer water advisory",
      "Builders break ground on new bridge project",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1983-07-23",
    real: "Airline jumbo glides to a runway on fumes",
    source: "The Gimli Glider, 1983 — a 767 ran out of fuel at 41,000 ft and glided to a runway with no lives lost.",
    link: "https://en.wikipedia.org/wiki/Gimli_Glider",
    fakes: [
      "Airline introduces new in-flight entertainment",
      "Pilot union negotiates new contract",
      "Airport adds second jet bridge to main terminal",
    ],
  },
  {
    segment: "Disasters",
    region: "Europe",
    era: "1810s",
    outlet: "Wikipedia",
    date: "1816-10-20",
    real: "Wave of beer crashes through a neighborhood, killing six",
    source: "The London Beer Flood, 1816 — a vat of porter burst at the Meux & Company brewery and a 30-ft wave of beer took six lives.",
    link: "https://en.wikipedia.org/wiki/London_Beer_Flood",
    fakes: [
      "Brewery expands output to meet winter demand",
      "City council approves new tavern licensing",
      "Local pub celebrates 200th anniversary",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1830s",
    outlet: "Wikipedia",
    date: "1835-08-25",
    real: "Newspaper reports giant creatures and cities on the Moon",
    source: "The Great Moon Hoax, 1835 — The New York Sun printed fake \u201ctelescope discoveries\u201d of moon life and the public believed it.",
    link: "https://en.wikipedia.org/wiki/Great_Moon_Hoax",
    fakes: [
      "Astronomy society publishes new star catalog",
      "University opens new observatory dome",
      "Telescope maker unveils sharper optics",
    ],
  },
  {
    segment: "History",
    region: "Europe",
    era: "1940s",
    outlet: "Wikipedia",
    date: "1943-04-30",
    real: "Allies fool an entire enemy army with a dead body",
    source: "Operation Mincemeat, 1943 — a drowned \u201cMajor\u201d carrying forged plans misdirected German forces away from the invasion of Sicily.",
    link: "https://en.wikipedia.org/wiki/Operation_Mincemeat",
    fakes: [
      "Intelligence service intercepts enemy radio traffic",
      "Naval command reroutes supply convoys",
      "Spy network dismantled in major operation",
    ],
  },
  {
    segment: "Disasters",
    region: "South America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2010-09-13",
    real: "33 miners rescued alive after 69 days underground",
    source: "Copiap\u00f3, Chile, 2010 — 33 men trapped by a mine collapse, brought up one by one after 69 days.",
    link: "https://en.wikipedia.org/wiki/2010_Copiap%C3%B3_mining_accident",
    fakes: [
      "Mining company announces new safety investment",
      "Rescue team completes routine drill in pit",
      "Industry group reviews accident prevention standards",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1500s",
    outlet: "Wikipedia",
    date: "1518-07-01",
    real: "Hundreds of people in a European town danced uncontrollably for weeks — some to death",
    source: "Strasbourg, 1518 — hundreds danced uncontrollably for weeks; dozens reportedly died of exhaustion, heart attack or stroke. Cause still debated.",
    link: "https://en.wikipedia.org/wiki/Dancing_plague_of_1518",
    fakes: [
      "Town holds festival celebrating 500th anniversary of mysterious dancing event",
      "Historians debunk long-held myth about 16th-century dancing outbreak",
      "Researchers propose new explanation for medieval mass hysteria",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "1960s",
    outlet: "Wikipedia",
    date: "1964-02-09",
    real: "Four lads from Liverpool outdraw every American TV program in history",
    source: "9 Feb 1964 — The Beatles appeared on The Ed Sullivan Show to ~73 million viewers, the largest TV audience in US history at the time.",
    link: "https://en.wikipedia.org/wiki/The_Beatles",
    fakes: [
      "British band announces reunion tour after decades apart",
      "TV network restores lost footage of historic 1964 broadcast",
      "Music critics rank 1964 among most influential years in pop",
    ],
  },
  {
    segment: "Sports",
    region: "Europe",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1974-07-01",
    real: "Hosts win the World Cup final in front of a record stadium crowd",
    source: "1974 FIFA World Cup final — West Germany beat the Netherlands 2–1 in Munich before ~89,000 fans, a final-day record for decades.",
    link: "https://en.wikipedia.org/wiki/1974_FIFA_World_Cup",
    fakes: [
      "Germany bids to host 2030 World Cup with new stadiums",
      "Historic 1974 final broadcast released in 4K for streaming",
      "Football historians debate whether 1974 was the greatest World Cup",
    ],
  },
  {
    segment: "History",
    region: "Africa",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1976-07-17",
    real: "Twenty-two African countries boycott the Olympics over one rugby tour",
    source: "1976 Montreal Olympics — 22 African nations boycotted in protest of New Zealand's rugby tour of apartheid-era South Africa.",
    link: "https://en.wikipedia.org/wiki/1976_Summer_Olympics",
    fakes: [
      "Olympic committee announces new unity initiative for upcoming Games",
      "Documentary explores the 1976 Olympic boycott",
      "Sports leaders call for renewed focus on fairness at the Games",
    ],
  },
  {
    segment: "History",
    region: "South America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1976-05-01",
    real: "26-year-old arrested for smuggling goes on to found the most notorious drug cartel in history",
    source: "1976 — Pablo Escobar was arrested by Colombian police after being caught with 39kg of cocaine; that same year he founded the Medellín Cartel.",
    link: "https://en.wikipedia.org/wiki/Pablo_Escobar",
    fakes: [
      "Colombian authorities arrest key figure in drug trafficking case",
      "New series dramatizes the fall of a 1980s crime boss",
      "Historian publishes book on the Medellín cartel",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1981-08-01",
    real: "New TV channel launches with a single music video — nobody expected it to last",
    source: "MTV launched 1 Aug 1981 with 'Video Killed the Radio Star' — the music video channel reshaped how the world consumes music.",
    link: "https://en.wikipedia.org/wiki/MTV",
    fakes: [
      "Cable network celebrates 40th anniversary with retrospective",
      "Music executives debate the future of video-first channels",
      "Archive releases lost footage from 1981 channel launch",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1982-09-29",
    real: "Seven strangers die after pills are laced with poison — one case that changed every package you open",
    source: "1982 — cyanide-laced Tylenol capsules in Chicago killed 7 people and forced the invention of tamper-evident packaging across the US.",
    link: "https://en.wikipedia.org/wiki/Chicago_Tylenol_murders",
    fakes: [
      "Pharmaceutical company recalls millions of pills after contamination",
      "Congress proposes new legislation to strengthen drug safety",
      "Forensic experts reopen 1982 poisoning investigation",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1973-12-01",
    real: "1973 movie predicts that in 2022, food is made from people",
    source: "Soylent Green (1973) is set in 2022 New York — its twist line 'Soylent Green is people' became one of cinema's most famous.",
    link: "https://en.wikipedia.org/wiki/Soylent_Green",
    fakes: [
      "New sci-fi film explores near-future food shortages in megacities",
      "Studio announces remake of classic 1970s dystopian thriller",
      "Cast reunites for 50th anniversary celebration of cult movie",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2005-08-29",
    real: "Category 5 hurricane turns a Gulf Coast city into a lake",
    source: "28 Aug 2005 — Hurricane Katrina made landfall as a Category 3 with a Category 5-strength storm surge; ~80% of New Orleans was underwater. Corrected to accurate phrasing: Katrina struck Aug 29, 2005, killing 1,800+ and flooding most of New Orleans.",
    link: "https://en.wikipedia.org/wiki/Hurricane_Katrina",
    fakes: [
      "Gulf Coast city marks 20th anniversary of Katrina landfall",
      "Engineers propose new levee design for hurricane season",
      "Storm chasers analyze Katrina as a textbook case study",
    ],
  },
  {
    segment: "Sports",
    region: "Asia",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2008-08-08",
    real: "Olympic opening ceremony fields 9,000 performers in front of a sell-out national stadium",
    source: "2008 Beijing Olympics — the opening ceremony featured roughly 9,000 performers and is widely cited as the most expensive and lavish ever staged.",
    link: "https://en.wikipedia.org/wiki/2008_Summer_Olympics",
    fakes: [
      "Beijing prepares to host 2022 Winter Olympics with new venues",
      "Documentary explores behind-the-scenes of the 2008 opening ceremony",
      "Olympic committee reviews spending from the 2008 Games",
    ],
  },
  {
    segment: "Sports",
    region: "Africa",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2010-06-11",
    real: "Africa hosts its first World Cup — and the host nation wins the opener",
    source: "2010 FIFA World Cup — the first held on African soil; host South Africa beat Mexico 1–0 in the opening match in Johannesburg.",
    link: "https://en.wikipedia.org/wiki/2010_FIFA_World_Cup",
    fakes: [
      "African nation bids to host 2030 World Cup with new stadiums",
      "Football historians rank 2010 World Cup among most memorable",
      "Local tourism board celebrates 15th anniversary of 2010 World Cup",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2011-03-11",
    real: "9.0 earthquake turns the ocean into a 40-meter wave that swallows a coastline",
    source: "11 Mar 2011 — a 9.0-magnitude quake off Japan generated a tsunami up to ~40m high, devastating Tohoku and triggering the Fukushima Daiichi meltdown.",
    link: "https://en.wikipedia.org/wiki/2011_T%C5%8Dhoku_earthquake_and_tsunami",
    fakes: [
      "Japan marks 10th anniversary of 2011 earthquake and tsunami",
      "Seismologists warn of increased risk along Pacific Ring of Fire",
      "Reconstruction project completes 15 years after 2011 disaster",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2011-05-01",
    real: "English town's annual race is runners chasing a rolling wheel of cheese — injuries every year",
    source: "Cooper's Hill Cheese-Rolling, Gloucestershire — hundreds chase a wheel of double-glopped cheese down a steep hillside; the slope is fast enough to knock spectators over, and injuries are a regular part of the event.",
    link: "https://en.wikipedia.org/wiki/Cheese_Rolling",
    fakes: [
      "English town cancels annual cheese-rolling event over safety concerns",
      "Local council proposes new rules for Cooper's Hill tradition",
      "Tourists flock to Gloucestershire for 500th anniversary of cheese rolling",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2014-03-08",
    real: "Jumbo jet with 239 people on board vanishes mid-flight — and is never found",
    source: "8 Mar 2014 — Malaysia Airlines Flight 370 disappeared over the southern Indian Ocean with 239 aboard; the main wreckage was never located.",
    link: "https://en.wikipedia.org/wiki/Malaysia_Airlines_Flight_370",
    fakes: [
      "Airlines announce new tracking rules for ocean-crossing flights",
      "Search team resumes hunt for missing jet after decade",
      "Investigation panel releases final report on 2014 disappearance",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2015-04-25",
    real: "7.8 earthquake flattens a Himalayan country's capital",
    source: "25 Apr 2015 — a 7.8-magnitude quake struck Nepal, killing 8,964 people and causing massive damage to historic sites in Kathmandu.",
    link: "https://en.wikipedia.org/wiki/2015_Nepal_earthquake",
    fakes: [
      "Nepal commemorates 10th anniversary of 2015 earthquake",
      "UN reports progress on reconstruction of damaged historic sites",
      "Seismologists study aftershocks following 2015 Nepal earthquake",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Oceania",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2016-03-01",
    real: "Great Barrier Reef bleaches white in the worst mass die-off on record",
    source: "2016–2017 — back-to-back mass bleaching events affected the Great Barrier Reef's shallow-water corals, the most severe in its recorded history.",
    link: "https://en.wikipedia.org/wiki/Great_Barrier_Reef",
    fakes: [
      "Marine biologists report signs of recovery in Great Barrier Reef",
      "Australia announces new conservation plan for Great Barrier Reef",
      "Tourism industry adapts to changing conditions in reef region",
    ],
  },
  {
    segment: "Internet",
    region: "Asia",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2021-09-17",
    real: "Death-game series becomes the most-watched show in streaming history",
    source: "Squid Game (2021) — the South Korean Netflix series became the most-watched show in Netflix history, with 140+ million households in its first 31 days.",
    link: "https://en.wikipedia.org/wiki/Squid_Game",
    fakes: [
      "Netflix announces Season 3 of Squid Game with new cast",
      "South Korean drama breaks streaming records with 100 million viewers",
      "Cultural analysts discuss global impact of 2021 streaming phenomenon",
    ],
  },
  {
    segment: "Business",
    region: "Global",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2021-02-08",
    real: "Internet joke coin crosses $1 trillion market cap for the first time",
    source: "February 2021 — bitcoin's market capitalization reached $1 trillion for the first time, the biggest milestone in the crypto era so far.",
    link: "https://en.wikipedia.org/wiki/Bitcoin",
    fakes: [
      "Crypto startup raises record funding round for AI trading bot",
      "Investment firms report record returns from digital asset portfolio",
      "Regulators propose new rules for cryptocurrency exchanges",
    ],
  },
  {
    segment: "History",
    region: "Global",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2022-01-23",
    real: "Nuclear experts set the world clock to 90 seconds from midnight — closest ever",
    source: "Jan 2022 — the Bulletin of the Atomic Scientists moved the Doomsday Clock to 90 seconds to midnight, the closest in its 75-year history.",
    link: "https://en.wikipedia.org/wiki/Doomsday_Clock",
    fakes: [
      "Bulletin of the Atomic Scientists updates Doomsday Clock for 2024",
      "Nuclear disarmament advocates call for renewed global cooperation",
      "Historical analysis examines 75 years of Doomsday Clock adjustments",
    ],
  },
  {
    segment: "Animals",
    region: "Europe",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1918-10-01",
    real: "A pigeon delivers a life-saving message after being shot through the chest",
    source: "1918 — Cher Ami, a French carrier pigeon, delivered a critical message from the 'Lost Battalion' in the Argonne Forest after being shot through the chest and losing a leg. She was awarded the Croix de Guerre.",
    link: "https://en.wikipedia.org/wiki/Cher_Ami",
    fakes: [
      "Veterans group honors legacy of First World War carrier pigeons",
      "New exhibit opens featuring medals awarded to military animals",
      "Historian revisits the role of animals in World War I",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1918-08-01",
    real: "A dog sniffs out a spy, saves his owner from poison, and wins a war medal",
    source: "World War I — Sergeant Stubby, a Boston Terrier mix, became the most decorated war dog of WWI, detecting gas attacks, spotting a spy, and reportedly saving his handler from a poisoned cake.",
    link: "https://en.wikipedia.org/wiki/Sergeant_Stubby",
    fakes: [
      "Veterans museum celebrates centenary of famous war dogs",
      "New book chronicles the bond between soldiers and their dogs",
      "Memorial unveiled for animals who served in the Great War",
    ],
  },
  {
    segment: "Animals",
    region: "Asia",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1925-05-01",
    real: "A dog waits at a train station every day for nine years for a dead owner",
    source: "Hachikō — the Japanese Akita who, after his owner's death in 1925, returned to the same Shibuya station every day for roughly nine years waiting for him to come home.",
    link: "https://en.wikipedia.org/wiki/Hachik%C5%8D",
    fakes: [
      "Tokyo station installs new pet-friendly waiting areas",
      "Behaviorist studies why dogs become attached to train stations",
      "City celebrates 100th anniversary of a famous dog statue",
    ],
  },
  {
    segment: "Animals",
    region: "Europe",
    era: "1950s",
    outlet: "Wikipedia",
    date: "1957-11-03",
    real: "A dog becomes the first living creature sent into orbit — and never comes home",
    source: "1957 — Laika, a stray dog, was launched into orbit aboard the Soviet Sputnik 2, becoming the first living being in orbit. She did not survive the mission.",
    link: "https://en.wikipedia.org/wiki/Laika",
    fakes: [
      "Space agency unveils new plans to send animals to the moon",
      "Scientists study effects of space travel on canine health",
      "Museum exhibit commemorates early space program animals",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2010-02-07",
    real: "A killer whale is tied to a string of deaths and becomes a global cause célèbre",
    source: "Tilikum — the orca at SeaWorld was involved in the deaths of several people, making him the center of a decades-long debate over keeping killer whales in captivity. He died in 2017.",
    link: "https://en.wikipedia.org/wiki/Tilikum",
    fakes: [
      "Theme park introduces new orca conservation education program",
      "Marine biologists release captive-trained whale into the ocean",
      "New report examines animal welfare in marine parks",
    ],
  },
  {
    segment: "Animals",
    region: "Australia",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1919-11-04",
    real: "A horse wins the richest race on Earth, then dies of a mysterious illness",
    source: "Phar Lap — the Australian thoroughbred who dominated racing in the 1920s, winning the Melbourne Cup and crossing into the US to beat top American horses before dying suddenly in 1932.",
    link: "https://en.wikipedia.org/wiki/Phar_Lap",
    fakes: [
      "Racing commission investigates cause of a famous horse's death",
      "Auction house sells memorabilia from a legendary racing era",
      "Veterinary team debunks old myth about racing horses",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1973-05-19",
    real: "A horse runs so fast that jockeys get carried to a record they still can't match",
    source: "Secretariat — in 1973 he swept the Triple Crown, winning the Belmont Stakes by an absurd 31 lengths in a time that is still considered one of the greatest in racing history.",
    link: "https://en.wikipedia.org/wiki/Secretariat",
    fakes: [
      "Racing fans celebrate anniversary of a record-breaking season",
      "Breeders eye offspring of a legendary racehorse for stud",
      "New documentary revisits the sport's most iconic horse",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1990-10-13",
    real: "A pet parrot keeps a word list of over a hundred — and uses them correctly",
    source: "Alex — an African Grey parrot studied by Dr. Irene Pepperberg learned over 100 words and could combine them meaningfully, a startling demonstration of avian cognition.",
    link: "https://en.wikipedia.org/wiki/Alex_(parrot)",
    fakes: [
      "Researchers publish new findings on parrot language ability",
      "Pet store reports surge in demand for talking birds",
      "Study compares intelligence of parrots and primates",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1972-07-01",
    real: "A gorilla learns to talk with her hands — and asks what's happening to her dead mother",
    source: "Koko — a western lowland gorilla taught sign language learned more than 1,000 signs and was famous for her emotional responses, including asking about the death of her mother.",
    link: "https://en.wikipedia.org/wiki/Koko_(gorilla)",
    fakes: [
      "Zoo celebrates 50th anniversary of a famous gorilla program",
      "Conservation group highlights progress in gorilla research",
      "New exhibit explores communication in great apes",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1960s",
    outlet: "Wikipedia",
    date: "1965-06-01",
    real: "A circus's killer whale becomes the most famous orca on the planet",
    source: "Shamu — the name SeaWorld gave to its star killer whales turned into a global brand, with the first 'Shamu' being an orca at the London Zoo in the 1960s before the name was adopted by marine parks.",
    link: "https://en.wikipedia.org/wiki/Shamu",
    fakes: [
      "Marine park retires its star whale from public shows",
      "Theme park unveils new orca habitat and feeding program",
      "Brand licensing deal announced for a famous animal name",
    ],
  },
  {
    segment: "Animals",
    region: "Global",
    era: "1900s",
    outlet: "Wikipedia",
    date: "1914-07-01",
    real: "An entire army of carrier pigeons goes to war to carry messages when radios fail",
    source: "War pigeon — homing pigeons were used on both sides of World War I and II to carry messages across battlefields when wireless and telephone lines were destroyed, and many were decorated for service.",
    link: "https://en.wikipedia.org/wiki/War_pigeon",
    fakes: [
      "Militaria exhibition showcases vintage military communication gear",
      "Historian traces the decline of carrier pigeon use in the army",
      "New study examines the reliability of pigeon messaging in war",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1919-01-15",
    real: "A 250-foot wall of molasses barrels bursts and chokes a Boston neighborhood",
    source: "1919 — the Great Molasses Flood in Boston: a giant storage tank ruptured, sending a 25- to 250-foot wave of molasses through the North End at up to 35 mph, killing 21 people.",
    link: "https://en.wikipedia.org/wiki/Great_Molasses_Flood",
    fakes: [
      "Boston fire crews race to save a warehouse full of syrup",
      "City declares emergency after record spill in the harbor district",
      "Residents report eerie sweet smell for days after storm",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "1900s",
    outlet: "Wikipedia",
    date: "1908-06-30",
    real: "A mystery blast levels 800 square miles of Siberian forest — no impact crater, no asteroid, no explanation",
    source: "1908 — the Tunguska event flattened an estimated 80 million trees across ~2,150 sq km of Siberia in a single airburst. No crater was found, and the cause was debated for a century.",
    link: "https://en.wikipedia.org/wiki/Tunguska_event",
    fakes: [
      "Scientists discover new type of meteorite in remote region",
      "Forestry service investigates sudden tree death in northern taiga",
      "Local reports describe strange lights and loud bang at dawn",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1917-12-06",
    real: "Two ships collide at 6:30 AM and level half a city in 23 seconds",
    source: "1917 — the Halifax Explosion: a munitions-laden ship and a supply vessel collided in Halifax harbor, producing the most powerful accidental explosion before nuclear weapons, killing roughly 1,600–2,000 people and destroying much of the city.",
    link: "https://en.wikipedia.org/wiki/Halifax_Explosion",
    fakes: [
      "Harbor workers warn of dangerous cargo pile-up near docks",
      "City braces for worst storm in a generation as ships take shelter",
      "Officials debate new safety rules for commercial shipping",
    ],
  },
  {
    segment: "Disasters",
    region: "Europe",
    era: "1960s",
    outlet: "Wikipedia",
    date: "1966-10-21",
    real: "A colliery tips into a village and buries a school mid-morning",
    source: "1966 — the Aberfan disaster: a coal waste tip above the Welsh village of Aberfan slid into the community, killing 116 people, 111 of them children at the local school.",
    link: "https://en.wikipedia.org/wiki/Aberfan_disaster",
    fakes: [
      "Miners union votes to halt operations over safety concerns",
      "Heavy rain triggers landslides across the Welsh valleys",
      "Government orders review of waste-tip regulations",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1984-12-03",
    real: "A pesticide plant leaks in the night and kills thousands in a sleeping city",
    source: "1984 — the Bhopal gas tragedy: a methyl isocyanate leak from a Union Carbide pesticide plant in Bhopal, India, killed thousands immediately and triggered decades of long-term illness.",
    link: "https://en.wikipedia.org/wiki/Bhopal_gas_tragedy",
    fakes: [
      "Factory workers report unusual smell and alarm before shift",
      "City hospital overwhelmed as residents seek treatment",
      "Corporate headquarters issues statement on facility safety",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1975-11-10",
    real: "A legendary freighter vanishes on Lake Superior with its entire crew in a single storm",
    source: "1975 — the SS Edmund Fitzgerald, a Great Lakes freighter, sank in a storm on Lake Superior, killing all 29 crew members. It became the subject of Gordon Lightfoot's famous song.",
    link: "https://en.wikipedia.org/wiki/SS_Edmund_Fitzgerald",
    fakes: [
      "Ship's family members launch search for the missing vessel",
      "Lakeshore towns mourn after storm claims lives",
      "Maritime authority investigates cause of the sinking",
    ],
  },
  {
    segment: "Disasters",
    region: "Europe",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1994-09-28",
    real: "A cruise ferry capsizes in the night and sinks in just 20 minutes",
    source: "1994 — the MS Estonia, a passenger ferry, capsized and sank in the Baltic Sea in under 20 minutes, killing 852 people — one of the worst maritime disasters in European history.",
    link: "https://en.wikipedia.org/wiki/MS_Estonia",
    fakes: [
      "Passengers report rough seas before ferry departs for Sweden",
      "Rescue crews mount massive operation in freezing waters",
      "Line faces scrutiny over vessel maintenance records",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1980-05-18",
    real: "A dormant volcano erupts without warning and flattens a town in minutes",
    source: "1980 — the eruption of Mount St. Helens in Washington state destroyed 600 square miles of forest, killed 57 people, and became the costliest volcanic eruption in U.S. history.",
    link: "https://en.wikipedia.org/wiki/Eruption_of_Mount_St._Helens",
    fakes: [
      "Geologists warn of increased seismic activity in the region",
      "Authorities evacuate thousands from surrounding valleys",
      "Airlines reroute flights around ash cloud",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "1800s",
    outlet: "Wikipedia",
    date: "1883-08-27",
    real: "An island volcano erupts so hard the shockwave circles the globe four times",
    source: "1883 — the eruption of Krakatoa in Indonesia was among the most powerful in recorded history; its shockwave was heard 3,000 miles away and the tsunami it triggered killed over 36,000 people.",
    link: "https://en.wikipedia.org/wiki/1883_eruption_of_Krakatoa",
    fakes: [
      "Merchants in distant ports report strange sounds overnight",
      "Naval vessels report unusual waves across the ocean",
      "Scientists debate source of the massive disturbance",
    ],
  },
  {
    segment: "Disasters",
    region: "Africa",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1986-08-21",
    real: "A lake exhales a cloud of carbon dioxide and kills 1,700 people in a single night",
    source: "1986 — the Lake Nyos disaster in Cameroon: a sudden release of carbon dioxide from the lake suffocated an estimated 1,700 people and thousands of animals in the surrounding villages.",
    link: "https://en.wikipedia.org/wiki/Lake_Nyos_disaster",
    fakes: [
      "Villagers report strange gas smell and falling livestock",
      "Researchers study unusual chemistry of the highland lake",
      "Government dispatches teams after mass casualties reported",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1981-07-17",
    real: "A hotel skywalk collapses in front of a crowd of dancers",
    source: "1981 — the Hyatt Regency walkway collapse in Kansas City: two suspended skywalks failed during a party, killing 114 people in what became a landmark case in structural engineering.",
    link: "https://en.wikipedia.org/wiki/Hyatt_Regency_walkway_collapse",
    fakes: [
      "Hotel hosts busy social event on its upper floors",
      "Engineers later review building's design documents",
      "Family of a victim files lawsuit against the developers",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2013-04-24",
    real: "A garment factory collapses in the middle of a work shift, killing 1,100",
    source: "2013 — the Rana Plaza collapse in Bangladesh: an eight-story garment factory building pancaked, killing 1,134 people and becoming the deadliest textile-industry disaster in history.",
    link: "https://en.wikipedia.org/wiki/Rana_Plaza_collapse",
    fakes: [
      "Workers report hairline cracks in the building overnight",
      "Factory owners refuse to allow evacuation before shift ends",
      "International brands distance themselves from the supplier",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1900s",
    outlet: "Wikipedia",
    date: "1906-04-18",
    real: "An earthquake hits at 5:12 AM and turns a city into a wall of fire",
    source: "1906 — the San Francisco earthquake struck at 5:12 AM, and the resulting fires burned for three days, destroying roughly 500 city blocks and killing hundreds to thousands.",
    link: "https://en.wikipedia.org/wiki/1906_San_Francisco_earthquake",
    fakes: [
      "Firefighters struggle as water mains rupture across the city",
      "Survivors flee to the waterfront to escape the flames",
      "Red Cross sets up aid camps for the displaced",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1800s",
    outlet: "Wikipedia",
    date: "1859-06-15",
    real: "Two armies stand off on the border over... a single shot pig",
    source: "1859 — the Pig War: a brief standoff between the U.S. and Britain over the San Juan Islands, triggered when an American farmer shot a British-owned pig that had been rooting in his potato field. It never escalated to real war.",
    link: "https://en.wikipedia.org/wiki/Pig_War",
    fakes: [
      "Border town braced as both nations send troops to the islands",
      "Diplomats rush to negotiate a ceasefire at the frontier",
      "Farmer arrested after confrontation with a rival settler",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1600s",
    outlet: "Wikipedia",
    date: "1631-01-01",
    real: "Two Italian cities go to war over the theft of a single bucket",
    source: "1631 — the War of the Bucket: a conflict between Bologna and Modena sparked, in part, by the theft of a sacred wooden bucket from Bologna's cathedral. Thousands died over a symbol.",
    link: "https://en.wikipedia.org/wiki/War_of_the_Bucket",
    fakes: [
      "Rival city denies involvement in the temple theft",
      "Citizens rally to defend the city's most sacred object",
      "Mediator proposes a truce to end the escalating feud",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "800s",
    outlet: "Wikipedia",
    date: "897-06-10",
    real: "The Pope puts the corpse of his predecessor on trial — and has it burned",
    source: "897 — the Cadaver Synod: the mummified body of Pope Formosus was dug up, dressed in papal vestments, seated on a throne, and put on trial by his successor, who was found guilty and had the corpse mutilated and drowned.",
    link: "https://en.wikipedia.org/wiki/Cadaver_Synod",
    fakes: [
      "Cardinals convene to address a disputed succession",
      "Relics of the late pontiff are moved to a new shrine",
      "Scholars debate the legality of the church's decision",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1917-10-01",
    real: "Two girls take a photo of fairies — and the world's most famous skeptic believes them",
    source: "1917 — the Cottingley Fairies: two cousins photographed what they claimed were fairies, and the images, backed by Arthur Conan Doyle, fooled the public into believing in real fairies for decades.",
    link: "https://en.wikipedia.org/wiki/Cottingley_Fairies",
    fakes: [
      "Village children show off a collection of strange photos",
      "Photographer offers to sell the images to a magazine",
      "Local paper runs a story on an unusual family hobby",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1920-01-01",
    real: "An unknown man spends decades gluing mysterious tiles into city streets",
    source: "Toynbee tiles: since the 1920s, an anonymous person has embedded small ceramic tiles with a cryptic message into the streets of cities across the Americas and Australia — a mystery that has never been solved.",
    link: "https://en.wikipedia.org/wiki/Toynbee_tiles",
    fakes: [
      "City workers report odd objects appearing in the pavement",
      "Historian traces the tiles to a local artisan",
      "Police investigate a possible hoax by a street vendor",
    ],
  },
  {
    segment: "Weird",
    region: "Asia",
    era: "1950s",
    outlet: "Wikipedia",
    date: "1959-02-02",
    real: "Nine hikers die on a snowy mountain under conditions that defy every explanation",
    source: "1959 — the Dyatlov Pass incident: nine experienced Soviet hikers died on the Ural mountains under mysterious circumstances, their tent cut from the inside and bodies scattered, spawning decades of theories.",
    link: "https://en.wikipedia.org/wiki/Dyatlov_Pass_incident",
    fakes: [
      "Rescue team launches search after hikers fail to check in",
      "Investigators reconstruct the group's route through the snow",
      "Local villagers report seeing strange lights on the ridge",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1980-11-26",
    real: "An army base in England reports repeated sightings of a 'craft' on a foggy forest",
    source: "1980 — the Rendlesham Forest incident: U.S. Air Force personnel stationed in Suffolk, England, reported multiple encounters with an unexplained object in a forest, calling it 'the closest thing to a UFO experience' they had seen.",
    link: "https://en.wikipedia.org/wiki/Rendlesham_Forest_incident",
    fakes: [
      "Airmen report unusual lights during a night training exercise",
      "Base security investigates a series of break-ins near the woods",
      "Officials deny rumors of a secret military facility in the area",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1912-01-01",
    real: "A 600-year-old book is written in a language no one can read — even today",
    source: "The Voynich manuscript: a 15th-century illustrated codex written in an unknown script and language. Despite centuries of attempts by cryptographers, no one has been able to decode it.",
    link: "https://en.wikipedia.org/wiki/Voynich_manuscript",
    fakes: [
      "Museum acquires a rare medieval text of unknown origin",
      "Linguists struggle to identify the script of an old codex",
      "Auction house lists a priceless book at record prices",
    ],
  },
  {
    segment: "Weird",
    region: "Global",
    era: "1800s",
    outlet: "Wikipedia",
    date: "1872-10-01",
    real: "A ship is found sailing with its engine running — and not a single soul on board",
    source: "The Mary Celeste: discovered adrift in the Atlantic in 1872 with the cargo intact and food still on the table, but the entire crew of 10 missing. Their fate was never explained.",
    link: "https://en.wikipedia.org/wiki/Mary_Celeste",
    fakes: [
      "Rescue vessel discovers a drifting boat with no crew aboard",
      "Mariners report a storm that scattered several ships",
      "Investigators search for the missing sailors' last known port",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1971-11-24",
    real: "A man jumps from a plane with $200,000 in cash — and is never found again",
    source: "1971 — D.B. Cooper: a man who called himself Dan Cooper hijacked a Boeing 737, took $200,000 in ransom, and parachuted out over the Pacific Northwest. He was never found.",
    link: "https://en.wikipedia.org/wiki/D.B._Cooper",
    fakes: [
      "Airlines tighten security after a passenger's unusual demand",
      "FBI launches a nationwide search for a missing hijacker",
      "Authorities ask the public for tips on the mysterious man",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1100s",
    outlet: "Wikipedia",
    date: "1150-01-01",
    real: "Two children appear in an English village with green skin — and speak no one's language",
    source: "The Green Children of Woolpit: a 12th-century legend in which two children, one with green skin, appeared in the village of Woolpit speaking an unknown language, and their origin is still debated.",
    link: "https://en.wikipedia.org/wiki/Green_children_of_Woolpit",
    fakes: [
      "Villagers take in two lost children found at the forest edge",
      "Priest struggles to communicate with the strange newcomers",
      "Local lord offers a reward for the children's missing family",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1600s",
    outlet: "Wikipedia",
    date: "1637-01-01",
    real: "Dutch traders pay the price of a house for a single flower bulb",
    source: "1637 — Tulip mania: in the Dutch Republic, tulip bulb prices skyrocketed to the value of a house before crashing, becoming the first recorded speculative bubble in financial history.",
    link: "https://en.wikipedia.org/wiki/Tulip_mania",
    fakes: [
      "Flower markets report record demand for rare bulbs",
      "Traders argue over the true value of a prized bloom",
      "Merchants warn of overheating in the horticulture trade",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1980-02-22",
    real: "A U.S. amateur hockey team beats the Soviet Union — the team that had never lost",
    source: "1980 — the 'Miracle on Ice': the U.S. Olympic hockey team, made of amateurs and college players, upset the heavily-favored Soviet Union 4-3 in Lake Placid, the night before the gold-medal game.",
    link: "https://en.wikipedia.org/wiki/Miracle_on_Ice",
    fakes: [
      "U.S. team named among the favorites heading into the Winter Games",
      "Soviet squad rolls through its group stage without dropping a period",
      "Crowd in the arena grows as the underdogs rally late",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "20th c.",
    outlet: "Wikipedia",
    date: "1956-05-22",
    real: "A pitcher retires all 27 batters in a game — a feat almost never done",
    source: "In baseball, a perfect game is the rarest of feats: a pitcher retires all 27 opposing batters with no hits, walks, or errors. Only a handful have ever been thrown in the modern era.",
    link: "https://en.wikipedia.org/wiki/Perfect_game_(baseball)",
    fakes: [
      "Star pitcher logs a career-best outing on a hot night",
      "Team celebrates a rare no-hitter after a tense final frame",
      "Rival pitcher retires 26 of 27 batters in a shutout",
    ],
  },
  {
    segment: "Sports",
    region: "Africa",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1974-10-30",
    real: "A retired champion comes out of retirement to beat the heavyweight in the jungle",
    source: "1974 — the 'Rumble in the Jungle': George Foreman, the heavyweight champion, was knocked out in the eighth round by Muhammad Ali in Kinshasa, Zaire, one of the greatest comebacks in boxing history.",
    link: "https://en.wikipedia.org/wiki/Rumble_in_the_Jungle",
    fakes: [
      "Champion trains in the African heat ahead of a title defense",
      "Local fans pack the stadium for the world's biggest fight",
      "Officials weigh in both fighters days before the main event",
    ],
  },
  {
    segment: "Sports",
    region: "Asia",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1975-10-01",
    real: "Two legends fight 14 brutal rounds in the heat — and the champ nearly doesn't survive",
    source: "1975 — the 'Thrilla in Manila': Muhammad Ali and Joe Frazier fought 14 exhausting rounds in the Manila heat; Frazier's corner stopped the fight after the 14th, and Ali was left barely able to walk.",
    link: "https://en.wikipedia.org/wiki/Thrilla_in_Manila",
    fakes: [
      "Two rivals agree to a third fight after years of rivalry",
      "Trainers warn both fighters about the dangerous heat",
      "Crowd in the ring roars as the final bell rings",
    ],
  },
  {
    segment: "Sports",
    region: "South America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1986-06-22",
    real: "A player scores a goal with his hand — and calls it the 'Hand of God'",
    source: "1986 — Diego Maradona's 'Hand of God': in the World Cup quarterfinal against England, Maradona punched the ball into the net, was caught on replay, and famously blamed the goal on 'a little bit of the hand of God.'",
    link: "https://en.wikipedia.org/wiki/Hand_of_God",
    fakes: [
      "Referee awards a controversial goal in the knockout round",
      "Replays later confirm the striker's arm was involved",
      "Manager insists the goal was perfectly legal",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "1900s",
    outlet: "Wikipedia",
    date: "1936-08-03",
    real: "A track star wins four golds in Nazi Berlin — right in Hitler's face",
    source: "1936 — Jesse Owens won four gold medals at the Berlin Olympics, shattering the Nazi myth of Aryan supremacy and becoming a global icon of athletic excellence and defiance.",
    link: "https://en.wikipedia.org/wiki/Jesse_Owens",
    fakes: [
      "American sprinter dominates the track events at the Games",
      "Host nation hosts a star-studded opening ceremony",
      "Owens sets new world records in the 100 and 200 meters",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1919-09-17",
    real: "Eight players on the 'champion' team are caught fixing the World Series",
    source: "1919 — the Black Sox scandal: eight members of the Chicago White Sox were convicted of throwing the World Series to the Cincinnati Reds for a share of the betting money, the sport's most infamous corruption case.",
    link: "https://en.wikipedia.org/wiki/1919_World_Series",
    fakes: [
      "Commissioner opens investigation into suspicious betting lines",
      "Star players quietly sell their tickets to the championship",
      "Court hears testimony from a bookie about a fix",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1995-09-06",
    real: "A player reaches 2,632 straight games played — a record that looks unbreakable",
    source: "Cal Ripken Jr. — in 1995 he broke Lou Gehrig's 56-year record of 2,130 consecutive games played and went on to finish at 2,632, a streak considered one of the hardest to break in sports.",
    link: "https://en.wikipedia.org/wiki/Cal_Ripken_Jr.",
    fakes: [
      "Shortstop chases a decades-old attendance record",
      "Team fans create a mural to honor the streak",
      "League debates new rules to protect players' health",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2004-10-27",
    real: "A team that was 0-3 in the series wins the World Series against all odds",
    source: "2004 — the Boston Red Sox completed the largest comeback in modern postseason history, erasing a 0-3 deficit against the New York Yankees to win the World Series, ending an 86-year title drought.",
    link: "https://en.wikipedia.org/wiki/2004_Boston_Red_Sox",
    fakes: [
      "Red Sox fall behind 0-3 in the ALCS against New York",
      "Fans pray the team can avoid a historic elimination",
      "Manager makes a bold bullpen call in the ninth inning",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "20th c.",
    outlet: "Wikipedia",
    date: "1950-01-01",
    real: "A 60-year-old baseball legend still hits like he's in his prime",
    source: "Babe Ruth — the 'Sultan of Swat' transformed baseball from a game of bunting into a game of home runs, and his record for career home runs stood for over 38 years.",
    link: "https://en.wikipedia.org/wiki/Babe_Ruth",
    fakes: [
      "Yankees star smashes a new single-season home run mark",
      "Fans pack Fenway Park to see the slugger in action",
      "Rival pitchers struggle to get a strike on the batter",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "20th c.",
    outlet: "Wikipedia",
    date: "1960-01-01",
    real: "A pitcher saves 600+ games — the most in baseball history",
    source: "Mariano Rivera — the 'Closer' finished his career with 652 saves, the most in Major League history, and was the first player from Puerto Rico inducted into the Baseball Hall of Fame.",
    link: "https://en.wikipedia.org/wiki/Mariano_Rivera",
    fakes: [
      "Yankees closer logs another career-best save",
      "Manager names him the top candidate for the Hall of Fame",
      "Rival teams study his signature changeup on video",
    ],
  },
  {
    segment: "Sports",
    region: "North America",
    era: "1900s",
    outlet: "Wikipedia",
    date: "1910-01-01",
    real: "A player hits .400 over a career — a mark almost no one has matched",
    source: "Ty Cobb — the 'Typhoid Cobb' finished his career with a .367 average but posted a single-season .406 in 1909, and his career hitting streak and baserunning ferocity made him the sport's most feared competitor.",
    link: "https://en.wikipedia.org/wiki/Ty_Cobb",
    fakes: [
      "Detroit star extends his hitting streak to a new record",
      "Opposing teams plot to slow down the baserunner",
      "League leaders debate new rules to curb his style",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1975-11-15",
    real: "Two hobbyists build a $600 computer in a garage — and kickstart the personal computer revolution",
    source: "1975 — the Altair 8800, a kit computer from MITS, is widely credited as the spark of the personal-computer revolution. A young Steve Wozniak and Steve Jobs soon built an interface for it, leading to the Apple I.",
    link: "https://en.wikipedia.org/wiki/Altair_8800",
    fakes: [
      "Hobbyist club showcases a new programmable machine",
      "Store sells a kit for tinkerers to build their own",
      "Engineers demonstrate a tiny processor on a workbench",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Global",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2000-01-01",
    real: "The world braces for a global tech meltdown at midnight — and the computers don't blow up",
    source: "Y2K — the 'bug' that made computers store the year as two digits loomed as a potential global catastrophe on Jan 1, 2000. Billions were spent on fixes, and it ended up being far less dramatic than feared.",
    link: "https://en.wikipedia.org/wiki/Y2K",
    fakes: [
      "Programmers race to fix a date-handling flaw before the new year",
      "Companies stockpile supplies in case of a systems blackout",
      "Officials urge calm as the clock approaches midnight",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Asia",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2003-01-01",
    real: "A country builds a 'Great Firewall' to keep the world's internet out",
    source: "The Great Firewall — China's system of internet censorship and surveillance, named after the Great Wall, blocks access to foreign websites and monitors online activity on a massive scale.",
    link: "https://en.wikipedia.org/wiki/The_Great_Firewall",
    fakes: [
      "Government rolls out new rules for overseas web access",
      "Tech firms adapt their sites to meet local regulations",
      "Researchers measure the reach of a national filter",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2013-01-01",
    real: "A company sends thousands of balloons into the stratosphere to give the world Wi-Fi",
    source: "Project Loon — Google's effort to provide internet access to remote areas using high-altitude balloons drifting in the stratosphere, some of which carried signals for years over Africa and the Pacific.",
    link: "https://en.wikipedia.org/wiki/Project_Loon",
    fakes: [
      "Startup tests a fleet of floating transmitters over the ocean",
      "Island communities gain their first high-speed connection",
      "Regulators clear a novel aerial communications network",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2017-09-15",
    real: "A space probe that orbited Saturn for 13 years deliberately dives into the planet to die",
    source: "Cassini — the NASA/ESA spacecraft that orbited Saturn for 13 years ended its mission in 2017 by plunging into the planet's atmosphere, destroying itself to protect potentially life-friendly moons.",
    link: "https://en.wikipedia.org/wiki/Cassini",
    fakes: [
      "Space agency ends a long mission with a controlled re-entry",
      "Probe's final images show the planet's rings in detail",
      "Scientists mourn the loss of a flagship observatory",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Global",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1977-09-05",
    real: "A probe launched in 1977 is still sending signals from the edge of the solar system",
    source: "Voyager 1 — launched in 1977, it flew past Jupiter and Saturn, and in 2012 became the first human-made object to reach interstellar space, still transmitting back to Earth decades later.",
    link: "https://en.wikipedia.org/wiki/Voyager_1",
    fakes: [
      "Probe crosses an invisible boundary into new space",
      "Mission control receives a signal after a decades-long silence",
      "Engineers keep a 40-year-old craft running with old code",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1990-04-24",
    real: "A $1.5 billion telescope launches — with a flaw that turns it into a national joke",
    source: "The Hubble Space Telescope launched in 1990 with a mirror ground the wrong shape, producing blurry images and heavy criticism — until a space-shuttle mission installed corrective optics in 1993.",
    link: "https://en.wikipedia.org/wiki/Hubble_Space_Telescope",
    fakes: [
      "Astronauts repair a flawed mirror on a giant observatory",
      "Telescope's first sharp images reveal distant galaxies",
      "Budget overruns draw fire before a costly rescue mission",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Europe",
    era: "Ancient",
    outlet: "Wikipedia",
    date: "100-01-01",
    real: "A 2,000-year-old 'computer' is pulled from a shipwreck — and baffles scientists",
    source: "The Antikythera mechanism — a 2nd-century-BCE Greek hand-powered device that predicted astronomical positions and eclipses, so advanced that comparable technology did not reappear for over 1,400 years.",
    link: "https://en.wikipedia.org/wiki/Antikythera_mechanism",
    fakes: [
      "Divers recover a mysterious bronze object from the wreck",
      "Researchers discover a gear system of unknown purpose",
      "Museum opens an exhibit on an ancient navigational tool",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1974-11-16",
    real: "Scientists point a giant radio dish at space and fire off a message to the stars",
    source: "1974 — the Arecibo message: a radio signal encoding human DNA and basic math was beamed toward a star cluster 25,000 light-years away, one of the first deliberate attempts to contact intelligent extraterrestrial life.",
    link: "https://en.wikipedia.org/wiki/Arecibo_message",
    fakes: [
      "Astronomers aim a massive dish at a distant star cluster",
      "Scientists encode a message in the pattern of pulses",
      "University hosts a public viewing of the transmission",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1978-03-21",
    real: "A radio shock jock reads a song with the word 'shit' 16 times — and the FCC is dragged to court",
    source: "1978 — FCC v. Pacifica Foundation: a court case over whether the FCC could regulate 'indecent' broadcasts, triggered by a radio show that played a track containing dozens of profanities during family listening hours.",
    link: "https://en.wikipedia.org/wiki/FCC_v._Pacifica_Foundation",
    fakes: [
      "Radio station airs a controversial track during daytime hours",
      "Regulators open a hearing on broadcast decency",
      "A listener's complaint sparks a landmark court ruling",
    ],
  },
  {
    segment: "Business",
    region: "North America",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2001-12-02",
    real: "A giant energy company vanishes — its books were fake and its executives are arrested",
    source: "2001 — Enron, one of America's largest energy companies, collapsed after years of accounting fraud, becoming the largest corporate bankruptcy in U.S. history and triggering the Sarbanes-Oxley Act.",
    link: "https://en.wikipedia.org/wiki/Enron",
    fakes: [
      "Energy giant reports record quarterly earnings",
      "Executives celebrate a merger with a rival utility",
      "Investors praise the company's bold new strategy",
    ],
  },
  {
    segment: "Business",
    region: "North America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2018-03-14",
    real: "A 'medical breakthrough' company turns out to have been a multi-year lie",
    source: "2018 — Theranos, the billion-dollar blood-testing startup led by Elizabeth Holmes, was exposed for faking its technology; it collapsed and Holmes was convicted of fraud.",
    link: "https://en.wikipedia.org/wiki/Theranos",
    fakes: [
      "Startup unveils a new blood test that uses a single drop",
      "Investors pour billions into the medical device firm",
      "Founder named one of the most influential young entrepreneurs",
    ],
  },
  {
    segment: "Business",
    region: "North America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2022-01-01",
    real: "A 'we work' real-estate giant valued at $47 billion turns out to be running at a huge loss",
    source: "WeWork — the co-working 'revolution' reached a $47 billion valuation before its failed 2019 IPO exposed a company that had been burning cash for years with no clear path to profit.",
    link: "https://en.wikipedia.org/wiki/WeWork",
    fakes: [
      "Co-working firm files for a record public offering",
      "Company rebrands its office spaces across major cities",
      "Founder shares a vision of reimagining the workplace",
    ],
  },
  {
    segment: "Business",
    region: "North America",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2020-04-20",
    real: "A $1.75 billion streaming service is shut down after just six months",
    source: "Quibi — a short-form streaming service backed by Hollywood stars and major investors launched in 2020 and was shut down just six months later after failing to gain a meaningful audience.",
    link: "https://en.wikipedia.org/wiki/Quibi",
    fakes: [
      "Streaming startup debuts with a lineup of celebrity originals",
      "Company bets big on short, vertical video for phones",
      "Investors back a new entrant in the crowded market",
    ],
  },
  {
    segment: "Business",
    region: "North America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2017-04-21",
    real: "A luxury 'paradise' festival for the rich turns out to be a complete scam",
    source: "2017 — the Fyre Festival: a high-society music festival in the Bahamas promised luxury to its attendees but delivered cardboard walls, a collapsed hotel, and no food — and its promoter was later sentenced to prison.",
    link: "https://en.wikipedia.org/wiki/Fyre_Festival",
    fakes: [
      "Billionaire-adjacent crowd arrives at a remote island party",
      "Promoters tout the festival's lavish new amenities",
      "Celebrities share glamorous photos from the beach",
    ],
  },
  {
    segment: "Business",
    region: "North America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2019-03-10",
    real: "A best-selling airplane is grounded worldwide after two fatal crashes",
    source: "The Boeing 737 MAX — two crashes in 2018 and 2019, linked to a faulty flight-control system, led to a global grounding of the type and billions in compensation for Boeing.",
    link: "https://en.wikipedia.org/wiki/Boeing_737_MAX",
    fakes: [
      "Airline orders a new batch of the popular narrow-body jet",
      "Regulators approve the aircraft for commercial service",
      "Airlines race to adopt the fuel-efficient model",
    ],
  },
  {
    segment: "Business",
    region: "Europe",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2015-09-18",
    real: "A giant auto maker is caught cheating on emissions tests worldwide",
    source: "2015 — the Volkswagen emissions scandal: the company was found to have used software to cheat pollution tests on diesel cars, affecting millions of vehicles and triggering a global recall.",
    link: "https://en.wikipedia.org/wiki/Volkswagen_emissions_scandal",
    fakes: [
      "Auto giant unveils a new line of clean diesel models",
      "Regulators tighten fuel-economy standards for new cars",
      "Engineers claim the vehicles meet all safety tests",
    ],
  },
  {
    segment: "Internet",
    region: "North America",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2003-01-01",
    real: "A faceless image board becomes the launchpad for memes and internet culture",
    source: "4chan — launched in 2003, the anonymous imageboard spawned countless internet memes, subcultures, and movements (including r/place-precursor events), and remains one of the internet's most influential — and controversial — sites.",
    link: "https://en.wikipedia.org/wiki/4chan",
    fakes: [
      "Anonymous users share an image board with no registration",
      "Site becomes the source of a viral wave of online jokes",
      "Moderators struggle to contain a surge of new subforums",
    ],
  },
  {
    segment: "Internet",
    region: "Global",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2020-01-01",
    real: "A bodybuilder's flexing photo becomes the internet's biggest 'chad' meme",
    source: "Gigachad — the image of the Austrian bodybuilder Julius Dober flexing his biceps became a dominant internet meme shorthand for stoic, over-the-top masculinity, spreading across TikTok and Twitter.",
    link: "https://en.wikipedia.org/wiki/Gigachad",
    fakes: [
      "A bodybuilder's flexing photo turns into a viral joke template",
      "The meme spreads across short-video platforms overnight",
      "Fans remix the image into hundreds of variations",
    ],
  },
  {
    segment: "Internet",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2014-10-20",
    real: "A simple sentence — 'YOLO' — becomes the defining phrase of a generation",
    source: "YOLO — the acronym for 'You Only Live Once' exploded from a 2011 Drake song into a ubiquitous catchphrase used (and misused) everywhere from social media to news headlines.",
    link: "https://en.wikipedia.org/wiki/YOLO",
    fakes: [
      "A catchy rap phrase takes over social media feeds",
      "The short slogan becomes a global catchphrase",
      "Brands rush to put the words on everything they sell",
    ],
  },
  {
    segment: "Internet",
    region: "North America",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2005-01-01",
    real: "A dancing baby on a website turns into one of the first viral videos",
    source: "Charlie Bit My Finger — a 2007 home video of a toddler biting his brother's finger became one of the most-viewed videos on YouTube, and one of the first to go truly, genuinely viral.",
    link: "https://en.wikipedia.org/wiki/Charlie_Bit_My_Finger",
    fakes: [
      "A home video of two kids racking up millions of views",
      "A family uploads a clip that the whole internet shares",
      "A short clip becomes the most-watched video on the platform",
    ],
  },
  {
    segment: "Internet",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2016-01-01",
    real: "A simple game where you slap a penguin becomes a global phenomenon",
    source: "Flappy Bird — a 2013 mobile game of a pixel bird dodging pipes became a massive viral hit, then was pulled from app stores by its own developer, becoming a symbol of internet fame's fickle nature.",
    link: "https://en.wikipedia.org/wiki/Flappy_Bird",
    fakes: [
      "A tiny mobile game with one button becomes wildly popular",
      "The developer suddenly removes the game from the store",
      "Players worldwide chase a high score on a simple app",
    ],
  },
  {
    segment: "Internet",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2013-02-01",
    real: "A 28-second dance video takes over the entire internet for two weeks",
    source: "2013 — the Harlem Shake: a dance meme that exploded across YouTube and social media, with thousands of parodies filmed in every possible setting, becoming one of the fastest-spreading viral phenomena ever.",
    link: "https://en.wikipedia.org/wiki/Harlem_Shake_(meme)",
    fakes: [
      "A short dance clip is remade by thousands of people",
      "The trend sweeps social media in a matter of days",
      "Companies rush to film their own version of the meme",
    ],
  },
  {
    segment: "Internet",
    region: "Global",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2020-09-01",
    real: "A single TikTok video turns a 20-year-old into a global star overnight",
    source: "TikTok — the short-form video app became a global phenomenon, turning unknown creators into international celebrities within days and reshaping how music, fashion, and news spread.",
    link: "https://en.wikipedia.org/wiki/TikTok",
    fakes: [
      "A short dance clip puts a creator on the map overnight",
      "Millions of users copy a new viral trend in hours",
      "A young artist's song tops the charts thanks to the app",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "1960s",
    outlet: "Wikipedia",
    date: "1969-08-18",
    real: "Half a million people gather in a muddy field for a three-day music festival",
    source: "Woodstock — in 1969, around 400,000 people gathered at a dairy farm in Bethel, New York for a three-day music festival that became a defining symbol of the 1960s counterculture.",
    link: "https://en.wikipedia.org/wiki/Woodstock",
    fakes: [
      "Organizers expect a small crowd for the weekend show",
      "Musicians line up for a record-setting three-day run",
      "Local farmers protest the influx of visitors to the farm",
    ],
  },
  {
    segment: "Music",
    region: "Global",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1985-07-13",
    real: "The world watches a benefit concert that raises hundreds of millions for famine",
    source: "Live Aid — in 1985, the dual-city benefit concerts (London and Philadelphia) raised an estimated $180 million for Ethiopian famine relief and became one of the most-watched live events in television history.",
    link: "https://en.wikipedia.org/wiki/Live_Aid",
    fakes: [
      "Stars agree to perform for free at a charity show",
      "Televised benefit raises a record sum for relief",
      "Fans in two cities watch the same lineup at the same time",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1977-09-01",
    real: "Two rival bands announce they're retiring at the same time — and the world loses it",
    source: "The 'Supergroup' era and band breakups — the 1970s saw a string of legendary splits (including bands like Led Zeppelin and Fleetwood Mac), with the era's final supergroup reunions becoming some of the most lucrative concerts ever.",
    link: "https://en.wikipedia.org/wiki/Fleetwood_Mac",
    fakes: [
      "Rival band announces a surprise reunion tour",
      "Veteran group breaks up after a final farewell show",
      "Fans petition for a one-night-only comeback concert",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1996-01-01",
    real: "A rap album goes double-platinum and changes the industry overnight",
    source: "1996 — The Notorious B.I.G.'s 'Life After Death' was released 12 days after his death, debuted at #1, and sold 1.8 million copies in its first week — one of the fastest-selling albums of all time.",
    link: "https://en.wikipedia.org/wiki/Life_After_Death",
    fakes: [
      "A rapper's final album is released weeks after his death",
      "The record debuts at the top of the charts",
      "Fans rush to buy the posthumous studio release",
    ],
  },
  {
    segment: "Music",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2015-08-08",
    real: "A song becomes the most-viewed video on the internet — and breaks the platform's records",
    source: "Despacito — Luis Fonsi's 2017 song (a collaboration with Daddy Yankee and Justin Bieber) became the first YouTube video to hit 5 billion views, and for a time the most-streamed track in history.",
    link: "https://en.wikipedia.org/wiki/Despacito",
    fakes: [
      "A reggaeton hit becomes the most-watched clip on the platform",
      "The song breaks streaming records across every service",
      "A remix with a pop star sends the track back to #1",
    ],
  },
  {
    segment: "Music",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2012-07-15",
    real: "A South Korean pop star's horse-riding dance takes over the entire internet",
    source: "2012 — 'Gangnam Style' by PSY became the first YouTube video to reach 1 billion views and one of the most-watched videos of all time, its 'horse dance' spawning a global meme phenomenon.",
    link: "https://en.wikipedia.org/wiki/Gangnam_Style",
    fakes: [
      "A pop video becomes the first to hit a billion views",
      "The song's signature dance is copied worldwide",
      "A music clip tops the charts across every continent",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2017-04-14",
    real: "A rapper's defiant single tops the charts and becomes a cultural moment",
    source: "2017 — 'HUMBLE.' by Kendrick Lamar topped the Billboard Hot 100 and became one of the defining tracks of the late 2010s, cementing his status as one of the genre's most influential artists.",
    link: "https://en.wikipedia.org/wiki/Humble_(Kendrick_Lamar_song)",
    fakes: [
      "A rapper's new single rockets to the top of the charts",
      "The track becomes a cultural moment overnight",
      "Critics debate whether the song is his best work yet",
    ],
  },
];
