// Question bank — "Which One's Real?" party game (v2)
// Each question: ONE verified real news story + 3 fakes.
// The real one is always the one that sounds the most fake.
//
// Tags (used by the filter stack):
//   segment — topic bucket (Animals, Sports, Disasters, ...)
//   region  — where it happened
//   era     — decade it happened
//   outlet  — where it's documented
//   date    — approximate ISO date of the event
// `link` is the verifiable source shown on the reveal.
// Every story in this bank has been manually verified against its source.
const QUESTIONS = [
  {
    segment: "Animals",
    region: "Australia",
    era: "1930s",
    outlet: "Wikipedia",
    date: "1932-10-01",
    real: "Army deploys machine guns in failed war against emus",
    source: "The Emu War, Western Australia, 1932 — the army lost to the birds.",
    link: "https://en.wikipedia.org/wiki/Emu_War",
    fakes: [
      "Farmers report record emu harvest after bumper season",
      "Village declares emergency after flock blocks main road",
      "New breeding program aims to boost local emu numbers",
    ],
  },
  {
    segment: "Business",
    region: "Europe",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2018-02-04",
    real: "KFC's UK chicken shortage so bad it swapped its logo for FCK",
    source: "Feb 2018 — a DHL logistics failure left KFC UK out of chicken for a week; the apology ads showed the logo rearranged as FCK.",
    link: "https://en.wikipedia.org/wiki/KFC",
    fakes: [
      "Fast food chain launches new spicy chicken burger",
      "Delivery app reports record holiday weekend orders",
      "Restaurant group cuts prices to win back customers",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1917-01-01",
    real: "Newspaper runs the headline \u201cMan bites dog\u201d in 1917",
    source: "A Belgian paper ran \u201cMan bites dog\u201d as a joke headline in 1917 — one of the earliest recorded uses.",
    link: "https://en.wikipedia.org/wiki/Man_bites_dog",
    fakes: [
      "Veterinarian warns about rising dog bite reports",
      "City passes new leash law for public parks",
      "Rescue group celebrates record dog adoptions",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1977-08-01",
    real: "Park ranger struck by lightning seven times — and lived",
    source: "Roy Sullivan, Shenandoah National Park ranger, survived seven strikes between 1942 and 1977 — Guinness-verified \u201chuman lightning rod\u201d.",
    link: "https://en.wikipedia.org/wiki/Roy_Sullivan",
    fakes: [
      "Meteorologists issue rare double-storm warning",
      "Lightning safety campaign hits record reach",
      "New sensor network tracks storms in real time",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1925-02-13",
    real: "Nation watches as thousands dig for a man trapped in a cave",
    source: "Floyd Collins, Kentucky, 1925 — a 20,000-person rescue effort made the cave collapse a national tragedy.",
    link: "https://en.wikipedia.org/wiki/Floyd_Collins",
    fakes: [
      "Caving group logs record-deep expedition in limestone",
      "Authorities close trail after rockfall warning",
      "Museum opens new exhibit on early explorers",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1997-07-18",
    real: "Alaska town names a 170-pound cat honorary mayor",
    source: "Stubbs of Talkeetna, Alaska — honorary mayor from 1997 until his death, drawing 30\u201340 visitors a day.",
    link: "https://en.wikipedia.org/wiki/Stubbs_(cat)",
    fakes: [
      "Vet opens new clinic to serve growing pet population",
      "Volunteers launch winter feeding program for strays",
      "Town council debates new rules on public pets",
    ],
  },
  {
    segment: "History",
    region: "North America",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1926-11-01",
    real: "Escape artist dies hours after a stranger punches his stomach",
    source: "Harry Houdini took a repeated punch to the abdomen during a strength-test stunt on Oct 31, 1926; he died the next morning.",
    link: "https://en.wikipedia.org/wiki/Harry_Houdini",
    fakes: [
      "Magician's estate settles long-running property dispute",
      "Celebrity chef announces new restaurant opening",
      "Veteran performer retires after 40-year career",
    ],
  },
  {
    segment: "Sports",
    region: "South America",
    era: "1950s",
    outlet: "Wikipedia",
    date: "1950-07-16",
    real: "Home fans watch their own team lose the World Cup final",
    source: "The Maracanazo, 1950 — Brazil lost the final at home to Uruguay in front of a stunned Maracan\u00e3 crowd.",
    link: "https://en.wikipedia.org/wiki/Uruguay_v_Brazil_(1950_FIFA_World_Cup)",
    fakes: [
      "Stadium sets record for largest single-match attendance",
      "National team announces new coach for next cycle",
      "Ticket prices scrapped after fan backlash",
    ],
  },
  {
    segment: "Sports",
    region: "South America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1986-06-22",
    real: "Player scores with his hand and calls it a gift from God",
    source: "Diego Maradona, 1986 World Cup — the \u201cHand of God\u201d goal, minutes before the Goal of the Century, same match.",
    link: "https://en.wikipedia.org/wiki/Diego_Maradona",
    fakes: [
      "Striker fined for simulating an injury",
      "Referee union introduces new card system",
      "Coach defends controversial last-minute substitution",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1997-05-11",
    real: "Computer beats the world chess champion for the first time",
    source: "May 1997 — Deep Blue became the first computer to beat the reigning world chess champion in a match.",
    link: "https://en.wikipedia.org/wiki/Deep_Blue_vs_Garry_Kasparov",
    fakes: [
      "Grandmaster wins tournament in record time",
      "Chess federation updates rating system",
      "New AI startup raises funding for board games",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1988-11-02",
    real: "Student's code infects a tenth of the internet in one weekend",
    source: "Robert Tappan Morris, 1988 — his \u201cworm\u201d hit roughly 10% of the connected internet, the first major one.",
    link: "https://en.wikipedia.org/wiki/Morris_worm",
    fakes: [
      "Security firm releases patch for popular email client",
      "University bans USB drives after data breach",
      "Tech giant unveils new antivirus product",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1999-09-23",
    real: "Space agency loses a mission because of one missing conversion",
    source: "Mars Climate Orbiter, 1999 — lost after one team worked in miles and another in meters.",
    link: "https://en.wikipedia.org/wiki/Mars_Climate_Orbiter",
    fakes: [
      "Rocket launch scrubbed over weather",
      "Mission control adds new safety checklist",
      "Probe sends back stunning images of red planet",
    ],
  },
  {
    segment: "Internet",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2017-07-01",
    real: "Millions of strangers paint on one giant shared canvas",
    source: "r/place, 2017 — over a million users placed ~16 million pixels on one 16,777,216-pixel canvas over 30 days.",
    link: "https://en.wikipedia.org/wiki/R/place",
    fakes: [
      "Museum opens digital art installation downtown",
      "Art collective launches collaborative mural project",
      "University students win design award for public art",
    ],
  },
  {
    segment: "History",
    region: "Europe",
    era: "1850s",
    outlet: "Wikipedia",
    date: "1858-06-15",
    real: "River stench so bad it shut down Parliament for a month",
    source: "The Great Stink, London 1858 — the Thames smelled so bad Parliament nearly moved; it forced the city's modern sewer system.",
    link: "https://en.wikipedia.org/wiki/Great_Stink",
    fakes: [
      "City council debates new waste collection route",
      "Health officials issue summer water advisory",
      "Builders break ground on new bridge project",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1983-07-23",
    real: "Airline jumbo glides to a runway on fumes",
    source: "The Gimli Glider, 1983 — a 767 ran out of fuel at 41,000 ft and glided to a runway with no lives lost.",
    link: "https://en.wikipedia.org/wiki/Gimli_Glider",
    fakes: [
      "Airline introduces new in-flight entertainment",
      "Pilot union negotiates new contract",
      "Airport adds second jet bridge to main terminal",
    ],
  },
  {
    segment: "Disasters",
    region: "Europe",
    era: "1810s",
    outlet: "Wikipedia",
    date: "1816-10-20",
    real: "Wave of beer crashes through a neighborhood, killing six",
    source: "The London Beer Flood, 1816 — a vat of porter burst at the Meux & Company brewery and a 30-ft wave of beer took six lives.",
    link: "https://en.wikipedia.org/wiki/London_Beer_Flood",
    fakes: [
      "Brewery expands output to meet winter demand",
      "City council approves new tavern licensing",
      "Local pub celebrates 200th anniversary",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1830s",
    outlet: "Wikipedia",
    date: "1835-08-25",
    real: "Newspaper reports giant creatures and cities on the Moon",
    source: "The Great Moon Hoax, 1835 — The New York Sun printed fake \u201ctelescope discoveries\u201d of moon life and the public believed it.",
    link: "https://en.wikipedia.org/wiki/Great_Moon_Hoax",
    fakes: [
      "Astronomy society publishes new star catalog",
      "University opens new observatory dome",
      "Telescope maker unveils sharper optics",
    ],
  },
  {
    segment: "History",
    region: "Europe",
    era: "1940s",
    outlet: "Wikipedia",
    date: "1943-04-30",
    real: "Allies fool an entire enemy army with a dead body",
    source: "Operation Mincemeat, 1943 — a drowned \u201cMajor\u201d carrying forged plans misdirected German forces away from the invasion of Sicily.",
    link: "https://en.wikipedia.org/wiki/Operation_Mincemeat",
    fakes: [
      "Intelligence service intercepts enemy radio traffic",
      "Naval command reroutes supply convoys",
      "Spy network dismantled in major operation",
    ],
  },
  {
    segment: "Disasters",
    region: "South America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2010-09-13",
    real: "33 miners rescued alive after 69 days underground",
    source: "Copiap\u00f3, Chile, 2010 — 33 men trapped by a mine collapse, brought up one by one after 69 days.",
    link: "https://en.wikipedia.org/wiki/2010_Copiap%C3%B3_mining_accident",
    fakes: [
      "Mining company announces new safety investment",
      "Rescue team completes routine drill in pit",
      "Industry group reviews accident prevention standards",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1500s",
    outlet: "Wikipedia",
    date: "1518-07-01",
    real: "Hundreds of people in a European town danced uncontrollably for weeks — some to death",
    source: "Strasbourg, 1518 — hundreds danced uncontrollably for weeks; dozens reportedly died of exhaustion, heart attack or stroke. Cause still debated.",
    link: "https://en.wikipedia.org/wiki/Dancing_plague_of_1518",
    fakes: [
      "Town holds festival celebrating 500th anniversary of mysterious dancing event",
      "Historians debunk long-held myth about 16th-century dancing outbreak",
      "Researchers propose new explanation for medieval mass hysteria",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "1960s",
    outlet: "Wikipedia",
    date: "1964-02-09",
    real: "Four lads from Liverpool outdraw every American TV program in history",
    source: "9 Feb 1964 — The Beatles appeared on The Ed Sullivan Show to ~73 million viewers, the largest TV audience in US history at the time.",
    link: "https://en.wikipedia.org/wiki/The_Beatles",
    fakes: [
      "British band announces reunion tour after decades apart",
      "TV network restores lost footage of historic 1964 broadcast",
      "Music critics rank 1964 among most influential years in pop",
    ],
  },
  {
    segment: "Sports",
    region: "Europe",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1974-07-01",
    real: "Hosts win the World Cup final in front of a record stadium crowd",
    source: "1974 FIFA World Cup final — West Germany beat the Netherlands 2–1 in Munich before ~89,000 fans, a final-day record for decades.",
    link: "https://en.wikipedia.org/wiki/1974_FIFA_World_Cup",
    fakes: [
      "Germany bids to host 2030 World Cup with new stadiums",
      "Historic 1974 final broadcast released in 4K for streaming",
      "Football historians debate whether 1974 was the greatest World Cup",
    ],
  },
  {
    segment: "History",
    region: "Africa",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1976-07-17",
    real: "Twenty-two African countries boycott the Olympics over one rugby tour",
    source: "1976 Montreal Olympics — 22 African nations boycotted in protest of New Zealand's rugby tour of apartheid-era South Africa.",
    link: "https://en.wikipedia.org/wiki/1976_Summer_Olympics",
    fakes: [
      "Olympic committee announces new unity initiative for upcoming Games",
      "Documentary explores the 1976 Olympic boycott",
      "Sports leaders call for renewed focus on fairness at the Games",
    ],
  },
  {
    segment: "History",
    region: "South America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1976-05-01",
    real: "26-year-old arrested for smuggling goes on to found the most notorious drug cartel in history",
    source: "1976 — Pablo Escobar was arrested by Colombian police after being caught with 39kg of cocaine; that same year he founded the Medellín Cartel.",
    link: "https://en.wikipedia.org/wiki/Pablo_Escobar",
    fakes: [
      "Colombian authorities arrest key figure in drug trafficking case",
      "New series dramatizes the fall of a 1980s crime boss",
      "Historian publishes book on the Medellín cartel",
    ],
  },
  {
    segment: "Music",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1981-08-01",
    real: "New TV channel launches with a single music video — nobody expected it to last",
    source: "MTV launched 1 Aug 1981 with 'Video Killed the Radio Star' — the music video channel reshaped how the world consumes music.",
    link: "https://en.wikipedia.org/wiki/MTV",
    fakes: [
      "Cable network celebrates 40th anniversary with retrospective",
      "Music executives debate the future of video-first channels",
      "Archive releases lost footage from 1981 channel launch",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1982-09-29",
    real: "Seven strangers die after pills are laced with poison — one case that changed every package you open",
    source: "1982 — cyanide-laced Tylenol capsules in Chicago killed 7 people and forced the invention of tamper-evident packaging across the US.",
    link: "https://en.wikipedia.org/wiki/Chicago_Tylenol_murders",
    fakes: [
      "Pharmaceutical company recalls millions of pills after contamination",
      "Congress proposes new legislation to strengthen drug safety",
      "Forensic experts reopen 1982 poisoning investigation",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1973-12-01",
    real: "1973 movie predicts that in 2022, food is made from people",
    source: "Soylent Green (1973) is set in 2022 New York — its twist line 'Soylent Green is people' became one of cinema's most famous.",
    link: "https://en.wikipedia.org/wiki/Soylent_Green",
    fakes: [
      "New sci-fi film explores near-future food shortages in megacities",
      "Studio announces remake of classic 1970s dystopian thriller",
      "Cast reunites for 50th anniversary celebration of cult movie",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2005-08-29",
    real: "Category 5 hurricane turns a Gulf Coast city into a lake",
    source: "28 Aug 2005 — Hurricane Katrina made landfall as a Category 3 with a Category 5-strength storm surge; ~80% of New Orleans was underwater. Corrected to accurate phrasing: Katrina struck Aug 29, 2005, killing 1,800+ and flooding most of New Orleans.",
    link: "https://en.wikipedia.org/wiki/Hurricane_Katrina",
    fakes: [
      "Gulf Coast city marks 20th anniversary of Katrina landfall",
      "Engineers propose new levee design for hurricane season",
      "Storm chasers analyze Katrina as a textbook case study",
    ],
  },
  {
    segment: "Sports",
    region: "Asia",
    era: "2000s",
    outlet: "Wikipedia",
    date: "2008-08-08",
    real: "Olympic opening ceremony fields 9,000 performers in front of a sell-out national stadium",
    source: "2008 Beijing Olympics — the opening ceremony featured roughly 9,000 performers and is widely cited as the most expensive and lavish ever staged.",
    link: "https://en.wikipedia.org/wiki/2008_Summer_Olympics",
    fakes: [
      "Beijing prepares to host 2022 Winter Olympics with new venues",
      "Documentary explores behind-the-scenes of the 2008 opening ceremony",
      "Olympic committee reviews spending from the 2008 Games",
    ],
  },
  {
    segment: "Sports",
    region: "Africa",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2010-06-11",
    real: "Africa hosts its first World Cup — and the host nation wins the opener",
    source: "2010 FIFA World Cup — the first held on African soil; host South Africa beat Mexico 1–0 in the opening match in Johannesburg.",
    link: "https://en.wikipedia.org/wiki/2010_FIFA_World_Cup",
    fakes: [
      "African nation bids to host 2030 World Cup with new stadiums",
      "Football historians rank 2010 World Cup among most memorable",
      "Local tourism board celebrates 15th anniversary of 2010 World Cup",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2011-03-11",
    real: "9.0 earthquake turns the ocean into a 40-meter wave that swallows a coastline",
    source: "11 Mar 2011 — a 9.0-magnitude quake off Japan generated a tsunami up to ~40m high, devastating Tohoku and triggering the Fukushima Daiichi meltdown.",
    link: "https://en.wikipedia.org/wiki/2011_T%C5%8Dhoku_earthquake_and_tsunami",
    fakes: [
      "Japan marks 10th anniversary of 2011 earthquake and tsunami",
      "Seismologists warn of increased risk along Pacific Ring of Fire",
      "Reconstruction project completes 15 years after 2011 disaster",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2011-05-01",
    real: "English town's annual race is runners chasing a rolling wheel of cheese — injuries every year",
    source: "Cooper's Hill Cheese-Rolling, Gloucestershire — hundreds chase a wheel of double-glopped cheese down a steep hillside; the slope is fast enough to knock spectators over, and injuries are a regular part of the event.",
    link: "https://en.wikipedia.org/wiki/Cheese_Rolling",
    fakes: [
      "English town cancels annual cheese-rolling event over safety concerns",
      "Local council proposes new rules for Cooper's Hill tradition",
      "Tourists flock to Gloucestershire for 500th anniversary of cheese rolling",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2014-03-08",
    real: "Jumbo jet with 239 people on board vanishes mid-flight — and is never found",
    source: "8 Mar 2014 — Malaysia Airlines Flight 370 disappeared over the southern Indian Ocean with 239 aboard; the main wreckage was never located.",
    link: "https://en.wikipedia.org/wiki/Malaysia_Airlines_Flight_370",
    fakes: [
      "Airlines announce new tracking rules for ocean-crossing flights",
      "Search team resumes hunt for missing jet after decade",
      "Investigation panel releases final report on 2014 disappearance",
    ],
  },
  {
    segment: "Disasters",
    region: "Asia",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2015-04-25",
    real: "7.8 earthquake flattens a Himalayan country's capital",
    source: "25 Apr 2015 — a 7.8-magnitude quake struck Nepal, killing 8,964 people and causing massive damage to historic sites in Kathmandu.",
    link: "https://en.wikipedia.org/wiki/2015_Nepal_earthquake",
    fakes: [
      "Nepal commemorates 10th anniversary of 2015 earthquake",
      "UN reports progress on reconstruction of damaged historic sites",
      "Seismologists study aftershocks following 2015 Nepal earthquake",
    ],
  },
  {
    segment: "Science & Tech",
    region: "Oceania",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2016-03-01",
    real: "Great Barrier Reef bleaches white in the worst mass die-off on record",
    source: "2016–2017 — back-to-back mass bleaching events affected the Great Barrier Reef's shallow-water corals, the most severe in its recorded history.",
    link: "https://en.wikipedia.org/wiki/Great_Barrier_Reef",
    fakes: [
      "Marine biologists report signs of recovery in Great Barrier Reef",
      "Australia announces new conservation plan for Great Barrier Reef",
      "Tourism industry adapts to changing conditions in reef region",
    ],
  },
  {
    segment: "Internet",
    region: "Asia",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2021-09-17",
    real: "Death-game series becomes the most-watched show in streaming history",
    source: "Squid Game (2021) — the South Korean Netflix series became the most-watched show in Netflix history, with 140+ million households in its first 31 days.",
    link: "https://en.wikipedia.org/wiki/Squid_Game",
    fakes: [
      "Netflix announces Season 3 of Squid Game with new cast",
      "South Korean drama breaks streaming records with 100 million viewers",
      "Cultural analysts discuss global impact of 2021 streaming phenomenon",
    ],
  },
  {
    segment: "Business",
    region: "Global",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2021-02-08",
    real: "Internet joke coin crosses $1 trillion market cap for the first time",
    source: "February 2021 — bitcoin's market capitalization reached $1 trillion for the first time, the biggest milestone in the crypto era so far.",
    link: "https://en.wikipedia.org/wiki/Bitcoin",
    fakes: [
      "Crypto startup raises record funding round for AI trading bot",
      "Investment firms report record returns from digital asset portfolio",
      "Regulators propose new rules for cryptocurrency exchanges",
    ],
  },
  {
    segment: "History",
    region: "Global",
    era: "2020s",
    outlet: "Wikipedia",
    date: "2022-01-23",
    real: "Nuclear experts set the world clock to 90 seconds from midnight — closest ever",
    source: "Jan 2022 — the Bulletin of the Atomic Scientists moved the Doomsday Clock to 90 seconds to midnight, the closest in its 75-year history.",
    link: "https://en.wikipedia.org/wiki/Doomsday_Clock",
    fakes: [
      "Bulletin of the Atomic Scientists updates Doomsday Clock for 2024",
      "Nuclear disarmament advocates call for renewed global cooperation",
      "Historical analysis examines 75 years of Doomsday Clock adjustments",
    ],
  },
];
