// Question bank — "Which One's Real?" party game (v2)
// Each question: ONE verified real news story + 3 fakes.
// The real one is always the one that sounds the most fake.
//
// Tags (used by the filter stack):
//   segment — topic bucket (Animals, Sports, Disasters, ...)
//   region  — where it happened
//   era     — decade it happened
//   outlet  — where it's documented
//   date    — approximate ISO date of the event
// `link` is the verifiable source shown on the reveal.
// Every story in this bank has been manually verified against its source.
const QUESTIONS = [
  {
    segment: "Animals",
    region: "Australia",
    era: "1930s",
    outlet: "Wikipedia",
    date: "1932-10-01",
    real: "Army deploys machine guns in failed war against emus",
    source: "The Emu War, Western Australia, 1932 — the army lost to the birds.",
    link: "https://en.wikipedia.org/wiki/Emu_War",
    fakes: [
      "Farmers report record emu harvest after bumper season",
      "Village declares emergency after flock blocks main road",
      "New breeding program aims to boost local emu numbers",
    ],
  },
  {
    segment: "Business",
    region: "Europe",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2018-02-04",
    real: "KFC's UK chicken shortage so bad it swapped its logo for FCK",
    source: "Feb 2018 — a DHL logistics failure left KFC UK out of chicken for a week; the apology ads showed the logo rearranged as FCK.",
    link: "https://en.wikipedia.org/wiki/KFC",
    fakes: [
      "Fast food chain launches new spicy chicken burger",
      "Delivery app reports record holiday weekend orders",
      "Restaurant group cuts prices to win back customers",
    ],
  },
  {
    segment: "Weird",
    region: "Europe",
    era: "1910s",
    outlet: "Wikipedia",
    date: "1917-01-01",
    real: "Newspaper runs the headline \u201cMan bites dog\u201d in 1917",
    source: "A Belgian paper ran \u201cMan bites dog\u201d as a joke headline in 1917 — one of the earliest recorded uses.",
    link: "https://en.wikipedia.org/wiki/Man_bites_dog",
    fakes: [
      "Veterinarian warns about rising dog bite reports",
      "City passes new leash law for public parks",
      "Rescue group celebrates record dog adoptions",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1970s",
    outlet: "Wikipedia",
    date: "1977-08-01",
    real: "Park ranger struck by lightning seven times — and lived",
    source: "Roy Sullivan, Shenandoah National Park ranger, survived seven strikes between 1942 and 1977 — Guinness-verified \u201chuman lightning rod\u201d.",
    link: "https://en.wikipedia.org/wiki/Roy_Sullivan",
    fakes: [
      "Meteorologists issue rare double-storm warning",
      "Lightning safety campaign hits record reach",
      "New sensor network tracks storms in real time",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1925-02-13",
    real: "Nation watches as thousands dig for a man trapped in a cave",
    source: "Floyd Collins, Kentucky, 1925 — a 20,000-person rescue effort made the cave collapse a national tragedy.",
    link: "https://en.wikipedia.org/wiki/Floyd_Collins",
    fakes: [
      "Caving group logs record-deep expedition in limestone",
      "Authorities close trail after rockfall warning",
      "Museum opens new exhibit on early explorers",
    ],
  },
  {
    segment: "Animals",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1997-07-18",
    real: "Alaska town names a 170-pound cat honorary mayor",
    source: "Stubbs of Talkeetna, Alaska — honorary mayor from 1997 until his death, drawing 30\u201340 visitors a day.",
    link: "https://en.wikipedia.org/wiki/Stubbs_(cat)",
    fakes: [
      "Vet opens new clinic to serve growing pet population",
      "Volunteers launch winter feeding program for strays",
      "Town council debates new rules on public pets",
    ],
  },
  {
    segment: "History",
    region: "North America",
    era: "1920s",
    outlet: "Wikipedia",
    date: "1926-11-01",
    real: "Escape artist dies hours after a stranger punches his stomach",
    source: "Harry Houdini took a repeated punch to the abdomen during a strength-test stunt on Oct 31, 1926; he died the next morning.",
    link: "https://en.wikipedia.org/wiki/Harry_Houdini",
    fakes: [
      "Magician's estate settles long-running property dispute",
      "Celebrity chef announces new restaurant opening",
      "Veteran performer retires after 40-year career",
    ],
  },
  {
    segment: "Sports",
    region: "South America",
    era: "1950s",
    outlet: "Wikipedia",
    date: "1950-07-16",
    real: "Home fans watch their own team lose the World Cup final",
    source: "The Maracanazo, 1950 — Brazil lost the final at home to Uruguay in front of a stunned Maracan\u00e3 crowd.",
    link: "https://en.wikipedia.org/wiki/Uruguay_v_Brazil_(1950_FIFA_World_Cup)",
    fakes: [
      "Stadium sets record for largest single-match attendance",
      "National team announces new coach for next cycle",
      "Ticket prices scrapped after fan backlash",
    ],
  },
  {
    segment: "Sports",
    region: "South America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1986-06-22",
    real: "Player scores with his hand and calls it a gift from God",
    source: "Diego Maradona, 1986 World Cup — the \u201cHand of God\u201d goal, minutes before the Goal of the Century, same match.",
    link: "https://en.wikipedia.org/wiki/Diego_Maradona",
    fakes: [
      "Striker fined for simulating an injury",
      "Referee union introduces new card system",
      "Coach defends controversial last-minute substitution",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1997-05-11",
    real: "Computer beats the world chess champion for the first time",
    source: "May 1997 — Deep Blue became the first computer to beat the reigning world chess champion in a match.",
    link: "https://en.wikipedia.org/wiki/Deep_Blue_vs_Garry_Kasparov",
    fakes: [
      "Grandmaster wins tournament in record time",
      "Chess federation updates rating system",
      "New AI startup raises funding for board games",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1988-11-02",
    real: "Student's code infects a tenth of the internet in one weekend",
    source: "Robert Tappan Morris, 1988 — his \u201cworm\u201d hit roughly 10% of the connected internet, the first major one.",
    link: "https://en.wikipedia.org/wiki/Morris_worm",
    fakes: [
      "Security firm releases patch for popular email client",
      "University bans USB drives after data breach",
      "Tech giant unveils new antivirus product",
    ],
  },
  {
    segment: "Science & Tech",
    region: "North America",
    era: "1990s",
    outlet: "Wikipedia",
    date: "1999-09-23",
    real: "Space agency loses a mission because of one missing conversion",
    source: "Mars Climate Orbiter, 1999 — lost after one team worked in miles and another in meters.",
    link: "https://en.wikipedia.org/wiki/Mars_Climate_Orbiter",
    fakes: [
      "Rocket launch scrubbed over weather",
      "Mission control adds new safety checklist",
      "Probe sends back stunning images of red planet",
    ],
  },
  {
    segment: "Internet",
    region: "Global",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2017-07-01",
    real: "Millions of strangers paint on one giant shared canvas",
    source: "r/place, 2017 — over a million users placed ~16 million pixels on one 16,777,216-pixel canvas over 30 days.",
    link: "https://en.wikipedia.org/wiki/R/place",
    fakes: [
      "Museum opens digital art installation downtown",
      "Art collective launches collaborative mural project",
      "University students win design award for public art",
    ],
  },
  {
    segment: "History",
    region: "Europe",
    era: "1850s",
    outlet: "Wikipedia",
    date: "1858-06-15",
    real: "River stench so bad it shut down Parliament for a month",
    source: "The Great Stink, London 1858 — the Thames smelled so bad Parliament nearly moved; it forced the city's modern sewer system.",
    link: "https://en.wikipedia.org/wiki/Great_Stink",
    fakes: [
      "City council debates new waste collection route",
      "Health officials issue summer water advisory",
      "Builders break ground on new bridge project",
    ],
  },
  {
    segment: "Disasters",
    region: "North America",
    era: "1980s",
    outlet: "Wikipedia",
    date: "1983-07-23",
    real: "Airline jumbo glides to a runway on fumes",
    source: "The Gimli Glider, 1983 — a 767 ran out of fuel at 41,000 ft and glided to a runway with no lives lost.",
    link: "https://en.wikipedia.org/wiki/Gimli_Glider",
    fakes: [
      "Airline introduces new in-flight entertainment",
      "Pilot union negotiates new contract",
      "Airport adds second jet bridge to main terminal",
    ],
  },
  {
    segment: "Disasters",
    region: "Europe",
    era: "1810s",
    outlet: "Wikipedia",
    date: "1816-10-20",
    real: "Wave of beer crashes through a neighborhood, killing six",
    source: "The London Beer Flood, 1816 — a vat of porter burst at the Meux & Company brewery and a 30-ft wave of beer took six lives.",
    link: "https://en.wikipedia.org/wiki/London_Beer_Flood",
    fakes: [
      "Brewery expands output to meet winter demand",
      "City council approves new tavern licensing",
      "Local pub celebrates 200th anniversary",
    ],
  },
  {
    segment: "Weird",
    region: "North America",
    era: "1830s",
    outlet: "Wikipedia",
    date: "1835-08-25",
    real: "Newspaper reports giant creatures and cities on the Moon",
    source: "The Great Moon Hoax, 1835 — The New York Sun printed fake \u201ctelescope discoveries\u201d of moon life and the public believed it.",
    link: "https://en.wikipedia.org/wiki/Great_Moon_Hoax",
    fakes: [
      "Astronomy society publishes new star catalog",
      "University opens new observatory dome",
      "Telescope maker unveils sharper optics",
    ],
  },
  {
    segment: "History",
    region: "Europe",
    era: "1940s",
    outlet: "Wikipedia",
    date: "1943-04-30",
    real: "Allies fool an entire enemy army with a dead body",
    source: "Operation Mincemeat, 1943 — a drowned \u201cMajor\u201d carrying forged plans misdirected German forces away from the invasion of Sicily.",
    link: "https://en.wikipedia.org/wiki/Operation_Mincemeat",
    fakes: [
      "Intelligence service intercepts enemy radio traffic",
      "Naval command reroutes supply convoys",
      "Spy network dismantled in major operation",
    ],
  },
  {
    segment: "Disasters",
    region: "South America",
    era: "2010s",
    outlet: "Wikipedia",
    date: "2010-09-13",
    real: "33 miners rescued alive after 69 days underground",
    source: "Copiap\u00f3, Chile, 2010 — 33 men trapped by a mine collapse, brought up one by one after 69 days.",
    link: "https://en.wikipedia.org/wiki/2010_Copiap%C3%B3_mining_accident",
    fakes: [
      "Mining company announces new safety investment",
      "Rescue team completes routine drill in pit",
      "Industry group reviews accident prevention standards",
    ],
  },
];
